name: Deploy to Surge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el código del repositorio
        uses: actions/checkout@v2

      - name: Instalar Surge
        run: npm install --global surge

      - name: Desplegar en Surge
        run: surge --project ./ --domain Pagina-web-continua.surge.sh --token ${{ secrets.SURGE_TOKEN }}
